name: quick_blue_platform_interface
description: A common platform interface for the quick_blue plugin.
version: 0.4.0-dev.0
homepage: https://github.com/woodemi/quick_blue
repository: https://github.com/woodemi/quick_blue/tree/master/quick_blue_platform_interface

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  # logging: ^1.2.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
